/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as BrainNourishmentRouteImport } from './routes/brain-nourishment'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CourseCourseIdRouteImport } from './routes/course.$courseId'

const BrainNourishmentRoute = BrainNourishmentRouteImport.update({
  id: '/brain-nourishment',
  path: '/brain-nourishment',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CourseCourseIdRoute = CourseCourseIdRouteImport.update({
  id: '/course/$courseId',
  path: '/course/$courseId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/brain-nourishment': typeof BrainNourishmentRoute
  '/course/$courseId': typeof CourseCourseIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/brain-nourishment': typeof BrainNourishmentRoute
  '/course/$courseId': typeof CourseCourseIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/brain-nourishment': typeof BrainNourishmentRoute
  '/course/$courseId': typeof CourseCourseIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/brain-nourishment' | '/course/$courseId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/brain-nourishment' | '/course/$courseId'
  id: '__root__' | '/' | '/brain-nourishment' | '/course/$courseId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BrainNourishmentRoute: typeof BrainNourishmentRoute
  CourseCourseIdRoute: typeof CourseCourseIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/brain-nourishment': {
      id: '/brain-nourishment'
      path: '/brain-nourishment'
      fullPath: '/brain-nourishment'
      preLoaderRoute: typeof BrainNourishmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/course/$courseId': {
      id: '/course/$courseId'
      path: '/course/$courseId'
      fullPath: '/course/$courseId'
      preLoaderRoute: typeof CourseCourseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BrainNourishmentRoute: BrainNourishmentRoute,
  CourseCourseIdRoute: CourseCourseIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
