/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as TimetableRouteImport } from './routes/timetable'
import { Route as MyCoursesRouteImport } from './routes/my-courses'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CourseCourseIdRouteImport } from './routes/course.$courseId'
import { Route as ApiVerifySolutionRouteImport } from './routes/api/verify-solution'

const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const TimetableRoute = TimetableRouteImport.update({
  id: '/timetable',
  path: '/timetable',
  getParentRoute: () => rootRouteImport,
} as any)
const MyCoursesRoute = MyCoursesRouteImport.update({
  id: '/my-courses',
  path: '/my-courses',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CourseCourseIdRoute = CourseCourseIdRouteImport.update({
  id: '/course/$courseId',
  path: '/course/$courseId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVerifySolutionRoute = ApiVerifySolutionRouteImport.update({
  id: '/api/verify-solution',
  path: '/api/verify-solution',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/my-courses': typeof MyCoursesRoute
  '/timetable': typeof TimetableRoute
  '/upload': typeof UploadRoute
  '/api/verify-solution': typeof ApiVerifySolutionRoute
  '/course/$courseId': typeof CourseCourseIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/my-courses': typeof MyCoursesRoute
  '/timetable': typeof TimetableRoute
  '/upload': typeof UploadRoute
  '/api/verify-solution': typeof ApiVerifySolutionRoute
  '/course/$courseId': typeof CourseCourseIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/my-courses': typeof MyCoursesRoute
  '/timetable': typeof TimetableRoute
  '/upload': typeof UploadRoute
  '/api/verify-solution': typeof ApiVerifySolutionRoute
  '/course/$courseId': typeof CourseCourseIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/my-courses'
    | '/timetable'
    | '/upload'
    | '/api/verify-solution'
    | '/course/$courseId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/my-courses'
    | '/timetable'
    | '/upload'
    | '/api/verify-solution'
    | '/course/$courseId'
  id:
    | '__root__'
    | '/'
    | '/my-courses'
    | '/timetable'
    | '/upload'
    | '/api/verify-solution'
    | '/course/$courseId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MyCoursesRoute: typeof MyCoursesRoute
  TimetableRoute: typeof TimetableRoute
  UploadRoute: typeof UploadRoute
  ApiVerifySolutionRoute: typeof ApiVerifySolutionRoute
  CourseCourseIdRoute: typeof CourseCourseIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timetable': {
      id: '/timetable'
      path: '/timetable'
      fullPath: '/timetable'
      preLoaderRoute: typeof TimetableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-courses': {
      id: '/my-courses'
      path: '/my-courses'
      fullPath: '/my-courses'
      preLoaderRoute: typeof MyCoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/course/$courseId': {
      id: '/course/$courseId'
      path: '/course/$courseId'
      fullPath: '/course/$courseId'
      preLoaderRoute: typeof CourseCourseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/verify-solution': {
      id: '/api/verify-solution'
      path: '/api/verify-solution'
      fullPath: '/api/verify-solution'
      preLoaderRoute: typeof ApiVerifySolutionRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MyCoursesRoute: MyCoursesRoute,
  TimetableRoute: TimetableRoute,
  UploadRoute: UploadRoute,
  ApiVerifySolutionRoute: ApiVerifySolutionRoute,
  CourseCourseIdRoute: CourseCourseIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
